return {
	hover = {
		Active = "scale-1.05 t-0.2 back" ,
		Inactive = "initial t-0.1 linear"
	},
	
	buildHovered = {
		Active = "sth-0.03 str-0.6 back",
		Inactive = "sth-0 str-1",
	},
	
	buildClicked = {
		Active = "sth-0.04 str-0 scale-1.02 back",
		Inactive = "sth-0 str-1 scale-1",
	},
	
	buttonHovered = {
		Active = "scale-1.1 t-0.2",
		Inactive = "initial t-0.2"
	},
	
	buttonClicked = {
		Active = "scale-0.95 t-0.15",
		Inactive = "initial t-0.15"
	},
	
	donationOptionsHovered = {
		Active = "scale-1.15 t-0.15",
		Inactive = "initial t-0.15"
	}
}